### ISSUE TITLE
`sel` module not working for iDRAC7 and iDRAC8.

### ISSUE THREAD

**Issue by perfectra1n** [mrlhansen/idrac_exporter#26]
Hey there,

Great project and thanks for making it. I was trying to deploy it in my homelab where I have a R430 (iDRAC 8) and an R420 (iDRAC 7). I was super interested in the `sel` module so that I could pull logs off of it and into Prometheus. Unfortunately I keep getting the following errors:
```
2023-06-10T23:35:31.141 INFO  Server listening on 0.0.0.0:9348
panic: interface conversion: interface {} is nil, not string
goroutine 40 [running]:
github.com/mrlhansen/idrac_exporter/internal/collector.(*xstring).UnmarshalJSON(0xc0002f6370, {0xc0002d18a2, 0x11, 0x255e})
	/app/src/internal/collector/unmarshal.go:35 +0x196
encoding/json.(*decodeState).array(0xc00025e3e8, {0x83ba80?, 0xc0002f6370?, 0x257b?})
	/usr/local/go/src/encoding/json/decode.go:507 +0x431
encoding/json.(*decodeState).value(0xc00025e3e8, {0x83ba80?, 0xc0002f6370?, 0x9?})
	/usr/local/go/src/encoding/json/decode.go:364 +0x7e
encoding/json.(*decodeState).object(0xc00025e3e8, {0x8bac40?, 0xc0002f6328?, 0xb?})
	/usr/local/go/src/encoding/json/decode.go:775 +0xd45
encoding/json.(*decodeState).value(0xc00025e3e8, {0x8bac40?, 0xc0002f6328?, 0x2e?})
	/usr/local/go/src/encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).array(0xc00025e3e8, {0x834320?, 0xc0001e5020?, 0x7d2e?})
	/usr/local/go/src/encoding/json/decode.go:562 +0x65b
encoding/json.(*decodeState).value(0xc00025e3e8, {0x834320?, 0xc0001e5020?, 0x7?})
	/usr/local/go/src/encoding/json/decode.go:364 +0x7e
encoding/json.(*decodeState).object(0xc00025e3e8, {0x8295c0?, 0xc0001e5000?, 0xc0001b7b90?})
	/usr/local/go/src/encoding/json/decode.go:775 +0xd45
encoding/json.(*decodeState).value(0xc00025e3e8, {0x8295c0?, 0xc0001e5000?, 0xc0001b7be0?})
	/usr/local/go/src/encoding/json/decode.go:374 +0x45
encoding/json.(*decodeState).unmarshal(0xc00025e3e8, {0x8295c0?, 0xc0001e5000?})
	/usr/local/go/src/encoding/json/decode.go:181 +0x1de
encoding/json.(*Decoder).Decode(0xc00025e3c0, {0x8295c0, 0xc0001e5000})
	/usr/local/go/src/encoding/json/stream.go:73 +0x191
github.com/mrlhansen/idrac_exporter/internal/collector.(*Client).redfishGet(0xc000128380, {0x8ea174?, 0x0?}, {0x8295c0, 0xc0001e5000})
	/app/src/internal/collector/client.go:301 +0x4f0
github.com/mrlhansen/idrac_exporter/internal/collector.(*Client).RefreshIdracSel(0xc000180600?, 0x0?, 0x0?)
	/app/src/internal/collector/client.go:202 +0x75
github.com/mrlhansen/idrac_exporter/internal/collector.(*Collector).Collect(0xc000104480, 0xc000051f60?)
	/app/src/internal/collector/collector.go:264 +0xad
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:455 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:466 +0x55d
```

This was running in a container container using the provided `Dockerfile`. 

When running the command:
```bash
curl -k https://idrac-metz.network/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel -u root | jq
```

I get the following back:
```
{
  "@odata.context": "/redfish/v1/$metadata#LogEntryCollection.LogEntryCollection",
  "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel",
  "@odata.type": "#LogEntryCollection.LogEntryCollection",
  "Description": "System Event Logs for this manager",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/34",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2023-05-23T06:22:59-05:00",
      "Description": " Log Entry 34",
      "EntryCode": [
        {
          "Member": "Transition to Non-Critical from OK"
        }
      ],
      "EntryType": "SEL",
      "Id": "34",
      "Links": {},
      "Message": "Correctable memory error rate exceeded for DIMM_A4.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "a1908",
      "Name": " Log Entry 34",
      "SensorNumber": 27,
      "SensorType": [
        {
          "Member": "Memory"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/33",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2023-04-10T00:47:37-05:00",
      "Description": " Log Entry 33",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "33",
      "Links": {},
      "Message": "The PERC1 battery is operating normally.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 33",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/32",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2023-04-10T00:25:58-05:00",
      "Description": " Log Entry 32",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "32",
      "Links": {},
      "Message": "The PERC1 battery is low.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 32",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/31",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2023-01-09T20:10:54-06:00",
      "Description": " Log Entry 31",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "31",
      "Links": {},
      "Message": "The PERC1 battery is operating normally.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 31",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/30",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2023-01-09T20:02:15-06:00",
      "Description": " Log Entry 30",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "30",
      "Links": {},
      "Message": "The PERC1 battery is low.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 30",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/29",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-10-11T19:40:35-05:00",
      "Description": " Log Entry 29",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "29",
      "Links": {},
      "Message": "The PERC1 battery is operating normally.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 29",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/28",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-10-11T19:07:05-05:00",
      "Description": " Log Entry 28",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "28",
      "Links": {},
      "Message": "The PERC1 battery is low.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 28",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/27",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-06-17T18:40:21-05:00",
      "Description": " Log Entry 27",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "27",
      "Links": {},
      "Message": "The chassis is closed while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 27",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/26",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-06-17T18:40:16-05:00",
      "Description": " Log Entry 26",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "26",
      "Links": {},
      "Message": "The chassis is open while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 26",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/25",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-04-07T15:23:51-05:00",
      "Description": " Log Entry 25",
      "EntryCode": [
        {
          "Member": "Transition to Critical from less severe"
        }
      ],
      "EntryType": "SEL",
      "Id": "25",
      "Links": {},
      "Message": "Correctable memory error rate exceeded for DIMM_A4.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "a2908",
      "Name": " Log Entry 25",
      "SensorNumber": 27,
      "SensorType": [
        {
          "Member": "Memory"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/24",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-03-18T16:26:58-05:00",
      "Description": " Log Entry 24",
      "EntryCode": [
        {
          "Member": "Transition to Non-Critical from OK"
        }
      ],
      "EntryType": "SEL",
      "Id": "24",
      "Links": {},
      "Message": "Correctable memory error rate exceeded for DIMM_A4.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "a1908",
      "Name": " Log Entry 24",
      "SensorNumber": 27,
      "SensorType": [
        {
          "Member": "Memory"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/23",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-01-14T06:48:24-06:00",
      "Description": " Log Entry 23",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "23",
      "Links": {},
      "Message": "The PERC1 battery is operating normally.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 23",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/22",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2022-01-14T06:27:53-06:00",
      "Description": " Log Entry 22",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "22",
      "Links": {},
      "Message": "The PERC1 battery is low.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 22",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/21",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-10-16T05:18:36-05:00",
      "Description": " Log Entry 21",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "21",
      "Links": {},
      "Message": "The PERC1 battery is operating normally.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 21",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/20",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-10-16T04:34:14-05:00",
      "Description": " Log Entry 20",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "20",
      "Links": {},
      "Message": "The PERC1 battery is low.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 20",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/19",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-07-18T02:39:30-05:00",
      "Description": " Log Entry 19",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "19",
      "Links": {},
      "Message": "The PERC1 battery is operating normally.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 19",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/18",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-07-18T01:48:37-05:00",
      "Description": " Log Entry 18",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "18",
      "Links": {},
      "Message": "The PERC1 battery is low.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 18",
      "SensorNumber": 104,
      "SensorType": [
        {
          "Member": "Battery"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/17",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-03-12T02:59:23-06:00",
      "Description": " Log Entry 17",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "17",
      "Links": {},
      "Message": "The chassis is closed while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 17",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/16",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2021-03-12T02:59:18-06:00",
      "Description": " Log Entry 16",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "16",
      "Links": {},
      "Message": "The chassis is open while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 16",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/15",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-10-19T18:05:25-05:00",
      "Description": " Log Entry 15",
      "EntryCode": [
        {
          "Member": "Transition to Non-Critical from OK"
        }
      ],
      "EntryType": "SEL",
      "Id": "15",
      "Links": {},
      "Message": "Correctable memory error rate exceeded for DIMM_A4.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "a1908",
      "Name": " Log Entry 15",
      "SensorNumber": 27,
      "SensorType": [
        {
          "Member": "Memory"
        }
      ],
      "Severity": "Warning"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/14",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-13T17:27:03-05:00",
      "Description": " Log Entry 14",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "14",
      "Links": {},
      "Message": "The chassis is closed while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 14",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/13",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-13T17:26:58-05:00",
      "Description": " Log Entry 13",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "13",
      "Links": {},
      "Message": "The chassis is open while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 13",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/12",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-08T14:33:38-05:00",
      "Description": " Log Entry 12",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "12",
      "Links": {},
      "Message": "Power supply 1 is absent.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "0ffff",
      "Name": " Log Entry 12",
      "SensorNumber": 98,
      "SensorType": [
        {
          "Member": "Power Supply / Converter"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/11",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-08T06:50:48-05:00",
      "Description": " Log Entry 11",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "11",
      "Links": {},
      "Message": "The power input for power supply 1 is lost.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "3ffff",
      "Name": " Log Entry 11",
      "SensorNumber": 98,
      "SensorType": [
        {
          "Member": "Power Supply / Converter"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/10",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-08T05:13:30-05:00",
      "Description": " Log Entry 10",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "10",
      "Links": {},
      "Message": "The power input for power supply 1 is lost.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "3ffff",
      "Name": " Log Entry 10",
      "SensorNumber": 98,
      "SensorType": [
        {
          "Member": "Power Supply / Converter"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/9",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-08T05:13:25-05:00",
      "Description": " Log Entry 9",
      "EntryCode": [
        {
          "Member": "Deassert"
        }
      ],
      "EntryType": "SEL",
      "Id": "9",
      "Links": {},
      "Message": "The chassis is closed while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 9",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/8",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-07-08T05:13:20-05:00",
      "Description": " Log Entry 8",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "8",
      "Links": {},
      "Message": "The chassis is open while the power is off.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "802ff",
      "Name": " Log Entry 8",
      "SensorNumber": 115,
      "SensorType": [
        {
          "Member": "Physical Chassis Security"
        }
      ],
      "Severity": "Critical"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/7",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T21:34:18-05:00",
      "Description": " Log Entry 7",
      "EntryCode": [
        {
          "Member": null
        }
      ],
      "EntryType": "SEL",
      "Id": "7",
      "Links": {},
      "Message": "OEM software event.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "2800",
      "Name": " Log Entry 7",
      "SensorNumber": 3,
      "SensorType": [
        {
          "Member": null
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/6",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T21:34:18-05:00",
      "Description": " Log Entry 6",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "6",
      "Links": {},
      "Message": "An OS graceful shut-down occurred.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "3ffff",
      "Name": " Log Entry 6",
      "SensorNumber": 0,
      "SensorType": [
        {
          "Member": "OS Stop/Shutdown"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/5",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T21:33:00-05:00",
      "Description": " Log Entry 5",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "5",
      "Links": {},
      "Message": "OEM software event.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "fa5e0",
      "Name": " Log Entry 5",
      "SensorNumber": 255,
      "SensorType": [
        {
          "Member": null
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/4",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T21:33:00-05:00",
      "Description": " Log Entry 4",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "4",
      "Links": {},
      "Message": "C: boot completed.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "1ffff",
      "Name": " Log Entry 4",
      "SensorNumber": 0,
      "SensorType": [
        {
          "Member": "BaseOSBoot/InstallationStatus"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/3",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T21:17:27-05:00",
      "Description": " Log Entry 3",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "3",
      "Links": {},
      "Message": "OEM software event.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "fa5e0",
      "Name": " Log Entry 3",
      "SensorNumber": 98,
      "SensorType": [
        {
          "Member": null
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/2",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T21:17:27-05:00",
      "Description": " Log Entry 2",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "2",
      "Links": {},
      "Message": "C: boot completed.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "1ffff",
      "Name": " Log Entry 2",
      "SensorNumber": 0,
      "SensorType": [
        {
          "Member": "BaseOSBoot/InstallationStatus"
        }
      ],
      "Severity": "OK"
    },
    {
      "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/Logs/Sel/1",
      "@odata.type": "#LogEntry.v1_3_0.LogEntry",
      "Created": "2020-06-29T20:57:59-05:00",
      "Description": " Log Entry 1",
      "EntryCode": [
        {
          "Member": "Assert"
        }
      ],
      "EntryType": "SEL",
      "Id": "1",
      "Links": {},
      "Message": "Log cleared.",
      "MessageArgs": [],
      "MessageArgs@odata.count": 0,
      "MessageId": "2ffff",
      "Name": " Log Entry 1",
      "SensorNumber": 114,
      "SensorType": [
        {
          "Member": "Event Logging Disabled"
        }
      ],
      "Severity": "OK"
    }
  ],
  "Members@odata.count": 34,
  "Name": "Log Entry Collection"
}
```

I wish I could help more, but I am absolute dogwater with Golang. Let me know if I can run any helpful cURL commands, or provide any additional. Hopefully this helps you resolve the issue, and thanks again for making this!

**Comment by mrlhansen** [comment]
Hi @perfectra1n 

Thanks for the very detailed report - I can see what the problem is. I will try to push a fix later today.

**Comment by mrlhansen** [comment]
I pushed a small fix. Let me know if it works now :)

**Comment by perfectra1n** [comment]
Awesome, it works perfectly now. Thanks so much! Now I can get those sweet, sweet logs into Prometheus 😆
