### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by samoz83** [mrlhansen/idrac_exporter#61]
We're running this on our estate that has a range of Dell, HP, and Gigabyte servers.

Seems certain versions of Gigabyte BMCs (12.61.17) cause invalid memory address errors:

```
SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x832ae1]

goroutine 16 [running]:
github.com/mrlhansen/idrac_exporter/internal/collector.(*Client).RefreshSystem(0xc0002b7950, 0x0?, 0xc000040f00?)
	/root/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.1.0/internal/collector/client.go:155 +0x121
github.com/mrlhansen/idrac_exporter/internal/collector.(*Collector).Collect(0xc00036ac60, 0xc000049760?)
	/root/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.1.0/internal/collector/collector.go:329 +0x3c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:455 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:466 +0x59d
```

Older BMC versions seem to work fine.

**Comment by mrlhansen** [comment]
Hi @samoz83 

I think I see what the problem is, but to be sure, could you send me the output from the following command?

```sh
curl -k https://IP-OF-MACHINE/redfish/v1/Systems/Self -u USERNAME
```

You will be prompted for a login password. I have never tried this on a Gigabyte machine, so I hope I got the URL address correct.

**Comment by mrlhansen** [comment]
The issue should be fixed now and I made a new release.

**Comment by samoz83** [comment]
Can confirm all working, thanks
