### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tqangxl** [mrlhansen/idrac_exporter#82]
PS D:\Lib\Software\moni\idrac_exporter\idrac_exporterwin> .\idrac_exporter.exe -config .\idrac.yml
2024-06-19T17:12:52.775 INFO  Build information: version= revision=
2024-06-19T17:12:52.784 INFO  Server listening on 0.0.0.0:9348
2024-06-19T17:41:54.546 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:42:37.293 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:43:02.310 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:43:27.312 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:43:52.305 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:44:17.340 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:44:42.307 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:45:07.315 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:45:32.315 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:45:57.338 ERROR Error instantiating metrics collector for host 192.168.1.110: Get "https://192.168.1.110/redfish/v1": dial tcp 192.168.1.110:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2024-06-19T17:46:01.275 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:46:26.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:46:51.276 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:47:16.280 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:47:41.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:48:06.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:48:31.274 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:48:56.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:49:21.277 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:49:46.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:50:11.273 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:50:36.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:51:01.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:51:26.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:51:51.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:52:16.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:52:41.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:53:06.272 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:53:31.285 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:53:56.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:54:21.269 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:54:46.285 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:55:11.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:55:36.276 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:56:01.280 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:56:26.285 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:56:51.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:57:16.276 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:57:41.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:58:06.276 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:58:31.275 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:58:56.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:59:21.275 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T17:59:46.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:00:11.284 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:00:36.285 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:01:01.279 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:01:26.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:01:51.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:02:16.278 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:02:41.272 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:03:06.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:03:31.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:03:56.282 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:04:21.282 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:04:46.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:05:11.284 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:05:36.276 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:06:01.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:06:26.278 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:06:51.271 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:07:16.284 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:07:41.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:08:06.269 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:08:31.273 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:08:56.285 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:09:21.282 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:09:46.275 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:10:11.270 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:10:36.271 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:11:01.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:11:26.272 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:11:51.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:12:16.275 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024-06-19T18:12:41.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024/06/19 18:13:00 http: panic serving [::1]:12049: runtime error: invalid memory address or nil pointer dereference
goroutine 104 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x12760c0?, 0x160b0b0?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mrlhansen/idrac_exporter/internal/config.(*RootConfig).GetHostCfg(0x162a5e0, {0xc00021f6c4, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/config/config.go:23 +0x10f
github.com/mrlhansen/idrac_exporter/internal/collector.GetCollector({0xc00021f6c4, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/collector/collector.go:477 +0x1b4
main.MetricsHandler({0x1398480, 0xc000229a40}, 0xc00028fd40)
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/cmd/idrac_exporter/handler.go:54 +0x1ce
net/http.HandlerFunc.ServeHTTP(0x162abd0?, {0x1398480?, 0xc000229a40?}, 0x10f2dda?)
        D:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xf070b9?, {0x1398480, 0xc000229a40}, 0xc00028fd40)
        D:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc0002834d0?}, {0x1398480?, 0xc000229a40?}, 0x6?)
        D:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000221c20, {0x1398c78, 0xc000089b90})
        D:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        D:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024/06/19 18:13:01 http: panic serving [::1]:12053: runtime error: invalid memory address or nil pointer dereference
goroutine 123 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x12760c0?, 0x160b0b0?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mrlhansen/idrac_exporter/internal/config.(*RootConfig).GetHostCfg(0x162a5e0, {0xc0001372d4, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/config/config.go:23 +0x10f
github.com/mrlhansen/idrac_exporter/internal/collector.GetCollector({0xc0001372d4, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/collector/collector.go:477 +0x1b4
main.MetricsHandler({0x1398480, 0xc0000e5180}, 0xc000162480)
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/cmd/idrac_exporter/handler.go:54 +0x1ce
net/http.HandlerFunc.ServeHTTP(0x162abd0?, {0x1398480?, 0xc0000e5180?}, 0x10f2dda?)
        D:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xf070b9?, {0x1398480, 0xc0000e5180}, 0xc000162480)
        D:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00014b230?}, {0x1398480?, 0xc0000e5180?}, 0x6?)
        D:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000292fc0, {0x1398c78, 0xc000089b90})
        D:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        D:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024/06/19 18:13:03 http: panic serving [::1]:12056: runtime error: invalid memory address or nil pointer dereference
goroutine 93 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x12760c0?, 0x160b0b0?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mrlhansen/idrac_exporter/internal/config.(*RootConfig).GetHostCfg(0x162a5e0, {0xc000137334, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/config/config.go:23 +0x10f
github.com/mrlhansen/idrac_exporter/internal/collector.GetCollector({0xc000137334, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/collector/collector.go:477 +0x1b4
main.MetricsHandler({0x1398480, 0xc0000e5260}, 0xc000300fc0)
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/cmd/idrac_exporter/handler.go:54 +0x1ce
net/http.HandlerFunc.ServeHTTP(0x162abd0?, {0x1398480?, 0xc0000e5260?}, 0x10f2dda?)
        D:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xf070b9?, {0x1398480, 0xc0000e5260}, 0xc000300fc0)
        D:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00030e780?}, {0x1398480?, 0xc0000e5260?}, 0x6?)
        D:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000129320, {0x1398c78, 0xc000089b90})
        D:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        D:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024-06-19T18:13:06.283 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
2024/06/19 18:13:08 http: panic serving [::1]:12063: runtime error: invalid memory address or nil pointer dereference
goroutine 124 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x12760c0?, 0x160b0b0?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mrlhansen/idrac_exporter/internal/config.(*RootConfig).GetHostCfg(0x162a5e0, {0xc000291184, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/config/config.go:23 +0x10f
github.com/mrlhansen/idrac_exporter/internal/collector.GetCollector({0xc000291184, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/collector/collector.go:477 +0x1b4
main.MetricsHandler({0x1398480, 0xc00029b420}, 0xc000301200)
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/cmd/idrac_exporter/handler.go:54 +0x1ce
net/http.HandlerFunc.ServeHTTP(0x162abd0?, {0x1398480?, 0xc00029b420?}, 0x10f2dda?)
        D:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xf070b9?, {0x1398480, 0xc00029b420}, 0xc000301200)
        D:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc00030e8a0?}, {0x1398480?, 0xc00029b420?}, 0x6?)
        D:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000293050, {0x1398c78, 0xc000089b90})
        D:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        D:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024/06/19 18:13:13 http: panic serving [::1]:12067: runtime error: invalid memory address or nil pointer dereference
goroutine 95 [running]:
net/http.(*conn).serve.func1()
        D:/Program Files/Go/src/net/http/server.go:1898 +0xbe
panic({0x12760c0?, 0x160b0b0?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/mrlhansen/idrac_exporter/internal/config.(*RootConfig).GetHostCfg(0x162a5e0, {0xc00021f9c4, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/config/config.go:23 +0x10f
github.com/mrlhansen/idrac_exporter/internal/collector.GetCollector({0xc00021f9c4, 0xd})
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/internal/collector/collector.go:477 +0x1b4
main.MetricsHandler({0x1398480, 0xc000229c00}, 0xc0003b2000)
        C:/Users/James/go/pkg/mod/github.com/mrlhansen/idrac_exporter@v1.3.0/cmd/idrac_exporter/handler.go:54 +0x1ce
net/http.HandlerFunc.ServeHTTP(0x162abd0?, {0x1398480?, 0xc000229c00?}, 0x10f2dda?)
        D:/Program Files/Go/src/net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0xf070b9?, {0x1398480, 0xc000229c00}, 0xc0003b2000)
        D:/Program Files/Go/src/net/http/server.go:2683 +0x1ad
net/http.serverHandler.ServeHTTP({0xc000283710?}, {0x1398480?, 0xc000229c00?}, 0x6?)
        D:/Program Files/Go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0001294d0, {0x1398c78, 0xc000089b90})
        D:/Program Files/Go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        D:/Program Files/Go/src/net/http/server.go:3285 +0x4b4
2024-06-19T18:13:31.281 ERROR Error instantiating metrics collector for host 192.168.1.110: host unreachable after 10 retries
PS D:\L

**Comment by mrlhansen** [comment]
Hi @tqangxl 

I am not sure exactly what part you are having issues with.

* The stack trace is the same issue I fixed in #80 and I will make a new release with this fix later this week.
* The errors relating to `192.168.1.110` are because the exporter cannot establish a connection. Are you sure the host is reachable?

**Comment by mrlhansen** [comment]
There is now a new release that fixes the panic.
